/**
 * Deterministic camouflage metrics from data/games.jsonl.
 *
 * Per config:
 *   - Round-indexed evil sabotage curve: share of evil quest actions that are
 *     'fail', for quest rounds 1-5.
 *   - Early-camouflage rate: share of evil quest actions in rounds 1-2 that are
 *     'success' (an evil player on a quest choosing NOT to sabotage).
 *
 * Reads only structured log fields (players[].role, quests[].actions).
 * Writes analysis/camouflage.md.
 *
 * Usage: npx tsx analysis/camouflage.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const EVIL_ROLES = new Set(['assassin', 'morgana', 'mordred', 'oberon', 'minion']);

interface GameLog {
  config: string;
  players: Array<{ id: number; role: string; model: string }>;
  quests: Array<{ round: number; actions: Record<string, 'success' | 'fail'> }>;
}

function pct(k: number, n: number): string {
  return n === 0 ? 'N/A' : ((k / n) * 100).toFixed(1) + '%';
}

const gamesFile = path.resolve('data/games.jsonl');
const games: GameLog[] = fs
  .readFileSync(gamesFile, 'utf-8')
  .trim()
  .split('\n')
  .map(l => JSON.parse(l));

// config -> round -> {evil, fail}
const byConfig = new Map<string, Map<number, { evil: number; fail: number }>>();
const configOrder: string[] = [];

for (const g of games) {
  if (!byConfig.has(g.config)) {
    byConfig.set(g.config, new Map());
    configOrder.push(g.config);
  }
  const rounds = byConfig.get(g.config)!;
  const evilIds = new Set(g.players.filter(p => EVIL_ROLES.has(p.role)).map(p => p.id));
  for (const q of g.quests) {
    if (!rounds.has(q.round)) rounds.set(q.round, { evil: 0, fail: 0 });
    const r = rounds.get(q.round)!;
    for (const [pid, action] of Object.entries(q.actions)) {
      if (!evilIds.has(parseInt(pid, 10))) continue;
      r.evil++;
      if (action === 'fail') r.fail++;
    }
  }
}

const lines: string[] = [];
lines.push('# Camouflage metrics (deterministic)');
lines.push('');
lines.push(`Generated by \`analysis/camouflage.ts\` from \`data/games.jsonl\` (${games.length} games).`);
lines.push('');
lines.push('Definitions: an "evil quest action" is a fail/success choice logged for a player with an');
lines.push('evil role who is on the executed quest team. Sabotage share = fail / evil actions in that');
lines.push('round. Early-camouflage rate = success / evil actions across rounds 1-2 (evil players');
lines.push('passing up an available sabotage while trust is being established).');
lines.push('');
lines.push('## Round-indexed evil sabotage curve (fail share among evil quest actions)');
lines.push('');
lines.push('| Config | R1 | R2 | R3 | R4 | R5 |');
lines.push('|---|---|---|---|---|---|');
for (const cfg of configOrder) {
  const rounds = byConfig.get(cfg)!;
  const cells = [1, 2, 3, 4, 5].map(rd => {
    const r = rounds.get(rd);
    return r && r.evil > 0 ? `${pct(r.fail, r.evil)} (${r.fail}/${r.evil})` : 'N/A';
  });
  lines.push(`| ${cfg} | ${cells.join(' | ')} |`);
}
lines.push('');
lines.push('## Early-camouflage rate (success share of evil quest actions, rounds 1-2)');
lines.push('');
lines.push('| Config | Evil actions (R1-2) | Camouflaged (success) | Early-camouflage rate |');
lines.push('|---|---|---|---|');
for (const cfg of configOrder) {
  const rounds = byConfig.get(cfg)!;
  let evil = 0;
  let fail = 0;
  for (const rd of [1, 2]) {
    const r = rounds.get(rd);
    if (r) {
      evil += r.evil;
      fail += r.fail;
    }
  }
  const succ = evil - fail;
  lines.push(`| ${cfg} | ${evil} | ${succ} | ${pct(succ, evil)} |`);
}
lines.push('');

const outPath = path.resolve('analysis/camouflage.md');
fs.writeFileSync(outPath, lines.join('\n'));
console.log(lines.join('\n'));
console.log(`\nWritten to ${outPath}`);
